### PR TITLE
Added European Tracks

### PR DESCRIPTION
**Pull request by pierre-trott**
This PR adds six tracks.
Track limits (left and right) have been constructed with Google Earth and exported to kml files (included). Both kml are post processed using fastest-lap Python command:

`fastest_lap.circuit_preprocessor(options)`

to produce a single .xml file included.

Tracks:
- Hungaroring
- Jarama
- Pau ville (city track)
- Vallelunga
- Varano
- Zolder

### CODE REVIEW

**Comment by juanmanzanero** [comment]
Hello!

Could you also attach [this notebook](https://github.com/juanmanzanero/fastest-lap/blob/main/examples/python/circuit_preprocessor/circuit_preprocessor.ipynb) applied to the tracks you sent? I want to set this as a requisite to collaborators uploading their tracks, but I have forgot to add it to [Contributing.md](https://github.com/juanmanzanero/fastest-lap/blob/main/CONTRIBUTING.md). If it is very inconvenient given the amount of tracks you have submitted, can you at least do it for pau_ville, vallelunga, and zolder? They seem to have large errors, though I am aware that the error measure is wrong for some tracks and the issue might be on my side.

Thank you very much for your very nice contribution, Pierre

**Comment by pierre-trott** [comment]
I don't have Jupyter running but I can find all the i_start and i_end for every corner and add all the plot commands in a circuit_preprocessor.ipynb. Would that be good?

You say the tracks have errors, what kind of error? What should I look for when plotting the tracks?

**Comment by juanmanzanero** [comment]
In each of the XML files produced there's a header with this information

```xml
    <header>
        <track_length units="m">3995.6606035603131</track_length>
        <L2_error_left>3.746581096896739</L2_error_left>
        <L2_error_right>1.9467386462668475</L2_error_right>
        <max_error_left>84.101605320233034</max_error_left>
        <max_error_right>61.549736514958695</max_error_right>
    </header>
```

This error is the distance between the approximation of the track through polynomials (what `circuit_preprocessor` creates) and the real KML files. I am aware that with certain geometries, the computation of the error is incorrect, which is probably the case. I will open an issue about this. This is why I want to see the jupyter notebooks. In these notebooks, I plot the KML paths against the circuit_preprocessor approximation to see if they match properly. 

If you cannot install Jupyter notebook, it is good enough if you can give me the i_start and i_end in notebooks and then I can run them myself, as you mention. Please call these notebooks as the name of the track (e.g. `jarama.ipynb`).

Thanks a lot!

Juan.

**Comment by juanmanzanero** [comment]
Yes, the correct syntax is 

```python
circuit = fastest_lap.load_track("../database/tracks/zolder/zolder.xml", track)
```

**Comment by pierre-trott** [comment]
I saw that load_track returns this value but in order to generate all the plots, I don't only need:
`s = fastest_lap.load_track("../database/tracks/zolder/zolder.xml", track)`
But also:
   `x = fastest_lap.download_vector("track/centerline/x")`
    `y = fastest_lap.download_vector("track/centerline/y")`
    `x_left = fastest_lap.download_vector("track/left/x")`
    `y_left = fastest_lap.download_vector("track/left/y")`
    `x_right = fastest_lap.download_vector("track/right/x")`
    `y_right = fastest_lap.download_vector("track/right/y")`
    `x_left_measured = fastest_lap.download_vector("track/left_measured/x")`
    `y_left_measured = fastest_lap.download_vector("track/left_measured/y")`
    `x_right_measured = fastest_lap.download_vector("track/right_measured/x")`
    `y_right_measured = fastest_lap.download_vector("track/right_measured/y")`
    `kappa = fastest_lap.download_vector("track/kappa")`
    `nl = fastest_lap.download_vector("track/nl")`
    `nr = fastest_lap.download_vector("track/nr")`
How do I get those?

**Comment by juanmanzanero** [comment]
Sorry again. I have opened an issue on this matter too.

**Comment by pierre-trott** [comment]
No worries, I understand that everything is still under construction.
I'm happy to help improve the tool

**Comment by pierre-trott** [comment]
New commit with the Notebooks for all tracks + Sachsenring.

Let me know if it's all okay.

**Review by juanmanzanero — APPROVED** [review]

**Comment by juanmanzanero** [comment]
Amazing! Thank you very much Pierre

**Pull request merged**
